// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AbortMerge(arg1) {
  return window['go']['main']['App']['AbortMerge'](arg1);
}

export function AbortRebase(arg1) {
  return window['go']['main']['App']['AbortRebase'](arg1);
}

export function AppendToGitignore(arg1, arg2) {
  return window['go']['main']['App']['AppendToGitignore'](arg1, arg2);
}

export function CheckoutRef(arg1, arg2) {
  return window['go']['main']['App']['CheckoutRef'](arg1, arg2);
}

export function CloseRepository(arg1) {
  return window['go']['main']['App']['CloseRepository'](arg1);
}

export function Commit(arg1, arg2, arg3) {
  return window['go']['main']['App']['Commit'](arg1, arg2, arg3);
}

export function ContinueRebase(arg1) {
  return window['go']['main']['App']['ContinueRebase'](arg1);
}

export function CreateBranch(arg1, arg2) {
  return window['go']['main']['App']['CreateBranch'](arg1, arg2);
}

export function CreateBranchAt(arg1, arg2, arg3) {
  return window['go']['main']['App']['CreateBranchAt'](arg1, arg2, arg3);
}

export function CreateTag(arg1, arg2, arg3) {
  return window['go']['main']['App']['CreateTag'](arg1, arg2, arg3);
}

export function DeleteBranch(arg1, arg2, arg3) {
  return window['go']['main']['App']['DeleteBranch'](arg1, arg2, arg3);
}

export function DeleteWorkingFile(arg1, arg2) {
  return window['go']['main']['App']['DeleteWorkingFile'](arg1, arg2);
}

export function DiscardFile(arg1, arg2) {
  return window['go']['main']['App']['DiscardFile'](arg1, arg2);
}

export function FetchAll(arg1) {
  return window['go']['main']['App']['FetchAll'](arg1);
}

export function GetAheadBehind(arg1) {
  return window['go']['main']['App']['GetAheadBehind'](arg1);
}

export function GetCommitDiff(arg1, arg2) {
  return window['go']['main']['App']['GetCommitDiff'](arg1, arg2);
}

export function GetCommitGraph(arg1, arg2) {
  return window['go']['main']['App']['GetCommitGraph'](arg1, arg2);
}

export function GetConflictContent(arg1, arg2) {
  return window['go']['main']['App']['GetConflictContent'](arg1, arg2);
}

export function GetFileAtCommitBase64(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetFileAtCommitBase64'](arg1, arg2, arg3);
}

export function GetFileBase64(arg1, arg2) {
  return window['go']['main']['App']['GetFileBase64'](arg1, arg2);
}

export function GetLastCommitSubject(arg1) {
  return window['go']['main']['App']['GetLastCommitSubject'](arg1);
}

export function GetMergeMessage(arg1) {
  return window['go']['main']['App']['GetMergeMessage'](arg1);
}

export function GetRebaseState(arg1) {
  return window['go']['main']['App']['GetRebaseState'](arg1);
}

export function GetStatus(arg1) {
  return window['go']['main']['App']['GetStatus'](arg1);
}

export function GetWorkingDiff(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetWorkingDiff'](arg1, arg2, arg3);
}

export function IsInMerge(arg1) {
  return window['go']['main']['App']['IsInMerge'](arg1);
}

export function IsInRebase(arg1) {
  return window['go']['main']['App']['IsInRebase'](arg1);
}

export function ListBranches(arg1) {
  return window['go']['main']['App']['ListBranches'](arg1);
}

export function ListOpenRepositories() {
  return window['go']['main']['App']['ListOpenRepositories']();
}

export function ListRecentRepositories() {
  return window['go']['main']['App']['ListRecentRepositories']();
}

export function LoadSession() {
  return window['go']['main']['App']['LoadSession']();
}

export function OpenInDefaultApp(arg1, arg2) {
  return window['go']['main']['App']['OpenInDefaultApp'](arg1, arg2);
}

export function OpenInEditor(arg1, arg2) {
  return window['go']['main']['App']['OpenInEditor'](arg1, arg2);
}

export function OpenRepository(arg1) {
  return window['go']['main']['App']['OpenRepository'](arg1);
}

export function OpenTerminal(arg1) {
  return window['go']['main']['App']['OpenTerminal'](arg1);
}

export function PickDirectory() {
  return window['go']['main']['App']['PickDirectory']();
}

export function PullBranch(arg1) {
  return window['go']['main']['App']['PullBranch'](arg1);
}

export function PushBranch(arg1) {
  return window['go']['main']['App']['PushBranch'](arg1);
}

export function PushNamedBranch(arg1, arg2) {
  return window['go']['main']['App']['PushNamedBranch'](arg1, arg2);
}

export function PushTag(arg1, arg2) {
  return window['go']['main']['App']['PushTag'](arg1, arg2);
}

export function RenameBranch(arg1, arg2, arg3) {
  return window['go']['main']['App']['RenameBranch'](arg1, arg2, arg3);
}

export function ResetBranch(arg1, arg2, arg3) {
  return window['go']['main']['App']['ResetBranch'](arg1, arg2, arg3);
}

export function ResolveConflict(arg1, arg2, arg3) {
  return window['go']['main']['App']['ResolveConflict'](arg1, arg2, arg3);
}

export function RevertCommit(arg1, arg2, arg3) {
  return window['go']['main']['App']['RevertCommit'](arg1, arg2, arg3);
}

export function SavePatchFile(arg1, arg2) {
  return window['go']['main']['App']['SavePatchFile'](arg1, arg2);
}

export function SaveSession(arg1, arg2) {
  return window['go']['main']['App']['SaveSession'](arg1, arg2);
}

export function ShowInFinder(arg1, arg2) {
  return window['go']['main']['App']['ShowInFinder'](arg1, arg2);
}

export function StageFile(arg1, arg2) {
  return window['go']['main']['App']['StageFile'](arg1, arg2);
}

export function StageHunk(arg1, arg2) {
  return window['go']['main']['App']['StageHunk'](arg1, arg2);
}

export function StartRebase(arg1, arg2) {
  return window['go']['main']['App']['StartRebase'](arg1, arg2);
}

export function Stash(arg1) {
  return window['go']['main']['App']['Stash'](arg1);
}

export function StashFile(arg1, arg2) {
  return window['go']['main']['App']['StashFile'](arg1, arg2);
}

export function StashPop(arg1) {
  return window['go']['main']['App']['StashPop'](arg1);
}

export function SwitchBranch(arg1, arg2, arg3) {
  return window['go']['main']['App']['SwitchBranch'](arg1, arg2, arg3);
}

export function UnstageFile(arg1, arg2) {
  return window['go']['main']['App']['UnstageFile'](arg1, arg2);
}

export function UnstageHunk(arg1, arg2) {
  return window['go']['main']['App']['UnstageHunk'](arg1, arg2);
}
