// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {repo} from '../models';
import {graph} from '../models';
import {main} from '../models';
import {gitcli} from '../models';

export function AbortMerge(arg1:string):Promise<void>;

export function AbortRebase(arg1:string):Promise<void>;

export function AppendToGitignore(arg1:string,arg2:string):Promise<void>;

export function ApplyStash(arg1:string,arg2:string):Promise<void>;

export function CheckoutRef(arg1:string,arg2:string):Promise<void>;

export function CloseRepository(arg1:string):Promise<void>;

export function Commit(arg1:string,arg2:string,arg3:boolean):Promise<void>;

export function ContinueRebase(arg1:string):Promise<void>;

export function CreateBranch(arg1:string,arg2:string):Promise<void>;

export function CreateBranchAt(arg1:string,arg2:string,arg3:string):Promise<void>;

export function CreateTag(arg1:string,arg2:string,arg3:string):Promise<void>;

export function DeleteBranch(arg1:string,arg2:string,arg3:boolean):Promise<void>;

export function DeleteWorkingFile(arg1:string,arg2:string):Promise<void>;

export function DiscardFile(arg1:string,arg2:string):Promise<void>;

export function DropStash(arg1:string,arg2:string):Promise<void>;

export function FetchAll(arg1:string):Promise<void>;

export function GetAheadBehind(arg1:string):Promise<repo.AheadBehind>;

export function GetCommitDiff(arg1:string,arg2:string):Promise<Array<repo.FileDiff>>;

export function GetCommitGraph(arg1:string,arg2:number):Promise<Array<graph.GraphRow>>;

export function GetConflictContent(arg1:string,arg2:string):Promise<repo.ConflictContent>;

export function GetFileAtCommitBase64(arg1:string,arg2:string,arg3:string):Promise<string>;

export function GetFileBase64(arg1:string,arg2:string):Promise<string>;

export function GetLastCommitSubject(arg1:string):Promise<string>;

export function GetMergeMessage(arg1:string):Promise<string>;

export function GetRebaseState(arg1:string):Promise<repo.RebaseState>;

export function GetStatus(arg1:string):Promise<Array<repo.FileStatus>>;

export function GetWorkingDiff(arg1:string,arg2:string,arg3:boolean):Promise<Array<repo.FileDiff>>;

export function IsInMerge(arg1:string):Promise<boolean>;

export function IsInRebase(arg1:string):Promise<boolean>;

export function ListBranches(arg1:string):Promise<Array<repo.BranchInfo>>;

export function ListOpenRepositories():Promise<Array<string>>;

export function ListRecentRepositories():Promise<Array<main.RecentRepo>>;

export function ListStashes(arg1:string):Promise<Array<gitcli.StashEntry>>;

export function LoadSession():Promise<repo.Session>;

export function MoveTag(arg1:string,arg2:string,arg3:string):Promise<void>;

export function OpenInDefaultApp(arg1:string,arg2:string):Promise<void>;

export function OpenInEditor(arg1:string,arg2:string):Promise<void>;

export function OpenRepository(arg1:string):Promise<void>;

export function OpenTerminal(arg1:string):Promise<void>;

export function PickDirectory():Promise<string>;

export function PopStash(arg1:string,arg2:string):Promise<void>;

export function PullBranch(arg1:string):Promise<void>;

export function PushBranch(arg1:string):Promise<void>;

export function PushNamedBranch(arg1:string,arg2:string):Promise<void>;

export function PushTag(arg1:string,arg2:string):Promise<void>;

export function RenameBranch(arg1:string,arg2:string,arg3:string):Promise<void>;

export function RenameStash(arg1:string,arg2:string,arg3:string):Promise<void>;

export function ResetBranch(arg1:string,arg2:string,arg3:string):Promise<void>;

export function ResolveConflict(arg1:string,arg2:string,arg3:string):Promise<void>;

export function RevertCommit(arg1:string,arg2:string,arg3:boolean):Promise<void>;

export function SavePatchFile(arg1:string,arg2:string):Promise<void>;

export function SaveSession(arg1:Array<repo.SessionTab>,arg2:number):Promise<void>;

export function ShowInFinder(arg1:string,arg2:string):Promise<void>;

export function StageFile(arg1:string,arg2:string):Promise<void>;

export function StageHunk(arg1:string,arg2:string):Promise<void>;

export function StartRebase(arg1:string,arg2:string):Promise<void>;

export function Stash(arg1:string):Promise<void>;

export function StashFile(arg1:string,arg2:string):Promise<void>;

export function StashPop(arg1:string):Promise<void>;

export function SwitchBranch(arg1:string,arg2:string,arg3:boolean):Promise<repo.SwitchResult>;

export function UnstageFile(arg1:string,arg2:string):Promise<void>;

export function UnstageHunk(arg1:string,arg2:string):Promise<void>;
